import { describe, it, expect, beforeAll, afterAll, afterEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { setupServer } from 'msw/node';
import { http, HttpResponse } from 'msw';
import { ToastProvider } from '../../../app/providers/ToastProvider.jsx';
import { ConfirmProvider } from '../../../app/providers/ConfirmProvider.jsx';
import { ManageStudents } from '../students/ManageStudents.jsx';

const API = 'http://localhost:4000/api';

const mockStudents = [
  {
    _id: 'stu1',
    id: 1,
    hoTen: 'Nguyễn Văn Active',
    email: 'active@edu.vn',
    className: '20DTH01',
    department: 'Công nghệ thông tin',
    userId: {
      _id: 'user1',
      email: 'active@edu.vn',
      status: 'Active',
      role: 'sinh-vien',
    },
  },
  {
    _id: 'stu2',
    id: 2,
    hoTen: 'Trần Thị Locked',
    email: 'locked@edu.vn',
    className: '20DTH02',
    department: 'Công nghệ thông tin',
    userId: {
      _id: 'user2',
      email: 'locked@edu.vn',
      status: 'Locked',
      lockReason: 'Vi phạm quy định',
      role: 'sinh-vien',
    },
  },
];

let lastStatusPayload = null;
let lastResetId = null;

const server = setupServer(
  http.get(`${API}/students`, () => {
    return HttpResponse.json({
      data: mockStudents,
      meta: { page: 1, pages: 1, total: 2 },
    });
  }),
  http.get(`${API}/departments`, () => {
    return HttpResponse.json({
      data: [{ _id: 'd1', id: 1, name: 'Công nghệ thông tin' }],
    });
  }),
  http.patch(`${API}/accounts/:id/status`, async ({ params, request }) => {
    lastStatusPayload = { id: params.id, body: await request.json() };
    return HttpResponse.json({ success: true });
  }),
  http.post(`${API}/accounts/:id/reset-password`, async ({ params }) => {
    lastResetId = params.id;
    return HttpResponse.json({ tempPassword: 'AutoGeneratedPass123!' });
  })
);

beforeAll(() => server.listen({ onUnhandledRequest: 'bypass' }));
afterEach(() => {
  server.resetHandlers();
  lastStatusPayload = null;
  lastResetId = null;
});
afterAll(() => server.close());

function renderWithProviders(ui) {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false, gcTime: 0 },
    },
  });

  return render(
    <QueryClientProvider client={queryClient}>
      <ToastProvider>
        <ConfirmProvider>{ui}</ConfirmProvider>
      </ToastProvider>
    </QueryClientProvider>
  );
}

describe('PersonManager inline account management', () => {
  it('renders student rows with status badges and quick action buttons', async () => {
    renderWithProviders(<ManageStudents />);

    expect(await screen.findByText('Nguyễn Văn Active')).toBeInTheDocument();
    expect(screen.getByText('Trần Thị Locked')).toBeInTheDocument();

    // Check account status badges
    expect(screen.getByText('Hoạt động')).toBeInTheDocument();
    expect(screen.getByText('Đã khóa')).toBeInTheDocument();

    // Check quick action buttons
    const lockButtons = screen.getAllByRole('button', { name: /^Khóa tài khoản$/i });
    expect(lockButtons.length).toBe(1);

    const unlockButtons = screen.getAllByRole('button', { name: /^Mở khóa tài khoản$/i });
    expect(unlockButtons.length).toBe(1);

    const resetButtons = screen.getAllByRole('button', { name: /đặt lại mật khẩu/i });
    expect(resetButtons.length).toBe(2);
  });

  it('opens lock modal when clicking lock button and submits status update', async () => {
    const user = userEvent.setup();
    renderWithProviders(<ManageStudents />);

    expect(await screen.findByText('Nguyễn Văn Active')).toBeInTheDocument();

    const lockBtn = screen.getByRole('button', { name: /^Khóa tài khoản$/i });
    await user.click(lockBtn);

    // Modal should be open
    expect(screen.getByText(/Khóa tài khoản của/i)).toBeInTheDocument();

    // Click confirm in modal
    const confirmLockBtn = screen.getByRole('button', { name: 'Xác nhận khóa' });
    await user.click(confirmLockBtn);

    await waitFor(() => {
      expect(lastStatusPayload).toEqual({
        id: 'user1',
        body: { status: 'Locked', lockReason: 'Vi phạm quy định' },
      });
    });
  });

  it('resets password and displays temporary password modal', async () => {
    const user = userEvent.setup();
    renderWithProviders(<ManageStudents />);

    expect(await screen.findByText('Nguyễn Văn Active')).toBeInTheDocument();

    const resetButtons = screen.getAllByRole('button', { name: /đặt lại mật khẩu/i });
    await user.click(resetButtons[0]);

    // Confirm dialog prompt
    const confirmBtn = await screen.findByRole('button', { name: 'Đặt lại' });
    await user.click(confirmBtn);

    // Temp password modal should display the password
    expect(await screen.findByText('Mật khẩu tạm thời')).toBeInTheDocument();
    expect(screen.getByText('AutoGeneratedPass123!')).toBeInTheDocument();
    expect(lastResetId).toBe('user1');
  });
});
